queue_rules:
  - name: dependabot-nsq-forward
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - -check-failure~=build-lint-test
      - check-success~=build-lint-test
      - check-success=security/snyk (iamolegga)

pull_request_rules:
  - name: merge pull requests from dependabot if CI passes
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - -check-failure~=build-lint-test
      - check-success~=build-lint-test
      - check-success=security/snyk (iamolegga)
    actions:
      queue:
        name: dependabot-nsq-forward
        method: rebase
